repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.18  # pin to a specific version
    hooks:
      - id: ruff-check #linter
        #types_or: [ python, pyi, pyproject ]
        args: [--fix] # optional: auto-fix fixable issues
      - id: ruff-format # formatter