import argparse
from bs4 import ResultSet, Tag
from datetime import datetime, timedelta, timezone, date
from dotenv import load_dotenv
from flask import Flask, render_template, request, redirect, url_for, flash, session, make_response, jsonify
from flask.typing import ResponseReturnValue
from functools import wraps
import hashlib
import hmac
import i18n
import json
import logging
from markupsafe import escape, Markup
import os
import re
import requests
import secrets
import subprocess
from zoneinfo import ZoneInfo


# Import my specific functions from other scripts
import conventus
from db import (
    connect_to_db,
    get_notifications,
    get_signout_list_from_db,
    get_member_signouts_from_db,
    add_signout_to_db,
    update_signout_by_id,
    save_pending_link,
    setup_notification,
    get_notifications_by_sid,
    get_coaches_to_notify,
    update_teams_for_notifications,
    delete_link_for_coach,
    get_team_info_from_db,
    add_team_info_to_db,
)
from exceptions import DatabaseError, ParsingError, SessionError, SiteError, NotificationError, MessengerError
import models
from shared import (
    get_paired_team_ids,
    get_pairing,
    get_pairing_from_team_id,
    path_handler,
    configure_flask_logger,
    configure_local_logger,
    date_std_to_da,
    localize_reason,
    LoginResult,
    TeamData,
    REQUEST_TIMEOUT,
)
from shared import PAIRED_TEAMS, CONVENTUS_CLUB_NAME, CONVENTUS_CLUB_ID, CONVENTUS_DEPT_ID, CONVENTUS_DEPT_NAME, SUPPORTED_LANGUAGES
from trace_logging import TraceLogger


load_dotenv()  # This loads variables from .env into os.environ
PAGE_ACCESS_TOKEN = os.environ.get('EIR_FB_ACCESS_TOKEN')

# logger and cache unbound before create_app is run
logger: TraceLogger = logging.getLogger(__name__)  # type: ignore[assignment]
# cache = Cache()


def create_app():
    app = Flask(__name__)

    # secret_key and logging, based on the FLASK_ENV
    flask_trace = False
    flask_debug = False
    if os.environ.get('FLASK_ENV') == 'production' or os.environ.get('FLASK_ENV') == 'prod':
        app.secret_key = os.environ.get('SECRET_KEY')  # this was generated by Render
    else:
        app.secret_key = os.environ.get('SECRET_KEY') or 'this is a long secret key used for testing, so my session does not constantly reset'
        flask_debug = True
        if os.environ.get('FLASK_ENV', '') == 'trace':
            flask_trace = True
    configure_flask_logger(debug=flask_debug, trace=flask_trace)
    logger.trace('trace logging on')

    # connect to the MongoDB
    connect_to_db()

    # translations
    i18n.load_path.append(path_handler('i18n_path'))
    i18n.set('file_format', 'json')
    i18n.set('skip_locale_root_data', True)
    i18n.set('fallback', 'en')

    return app


app = create_app()


def get_locale():
    # This automatically parses the Accept-Language header
    # Adjust the SUPPORTED_LANGUAGES list to match your available JSON filenames
    return request.accept_languages.best_match(SUPPORTED_LANGUAGES) or 'en'


@app.before_request
def set_request_locale():
    # Detect from Accept-Language header
    i18n.set('locale', get_locale())


@app.context_processor
def inject_t():
    # This makes {{ t('...') }} available in every HTML template
    return dict(t=i18n.t)


def simple_flash_fmt(text: str) -> str:
    # Converts literal newlines into HTML breaks
    return Markup(escape(text).replace('\n', '<br>'))


@app.route('/cronjob_82489.html')
def chronjob():
    return 'cronjob.de'


def require_session_keys(*keys, redirect_to='login_c'):
    def decorator(f):
        @wraps(f)
        def wrapper(*args, **kwargs):
            if request.method == 'OPTIONS':
                return f(*args, **kwargs)  # no session keys to verify for OPTIONS
            missing = [key for key in keys if not session.get(key)]
            if missing:
                logger.debug(f'Missing or empty session keys: {missing}, redirecting to login')
                flash(i18n.t('app.no_active_session'), 'danger')
                return redirect(url_for(redirect_to))
            return f(*args, **kwargs)

        return wrapper

    return decorator


@app.before_request
def enforce_session_expiry():
    expires_at = session.get('expires_at')
    if expires_at is not None:
        # datetimes pulled back out of the session are already tz-aware, if they were stored tz-aware
        if datetime.now(timezone.utc) >= expires_at:
            session.clear()
            # optionally: flash a message, redirect to login, etc.
            flash(i18n.t('app.session_expired'), 'danger')


@app.route('/')
def home():
    if get_locale() == 'da':
        return render_template('index_da.html')
    return render_template('index.html')


@app.route('/privacypolicy')
@app.route('/privacy-policy')
@app.route('/privacy_policy')
def privacy_policy():
    return render_template('privacy_policy.html')


@app.route('/member_instructions')
def member_instructions():
    return render_template('member_instructions.html')


@app.route('/coach_instructions')
def coach_instructions():
    return render_template('coach_instructions.html')


@app.route('/medlemsvejledning')
def medlemsvejledning():
    return render_template('medlemsvejledning.html')


@app.route('/traenervejledning')
def traenervejledning():
    return render_template('traenervejledning.html')


@app.route('/locale')
def show_locale():
    html = f"""<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{i18n.t('app.checkin_menu_title')}</title>
        <link rel="stylesheet" href="{url_for('static', filename='styles.css')}">
    </head>
    <body>"""
    html += f"""        <p>{i18n.t('app.locale_best_match', lingua=get_locale())}</p>
    </body>
</html>"""
    return html


@app.route('/coach')
def login_c():
    if session.get('PHPSESSID') and session.get('username') and session.get('teams'):
        s = set_session_cookie_for_requests()
        if conventus.coach_login_check(s.cookies, request.headers):
            return redirect(url_for('main_menu', user=session.get('username')))  # Redirect to main menu if an active session exists
    logger.trace('Rendering coach login page')
    return render_template('coach_login.html')


@app.route('/login', methods=['POST'])
def coach_login():
    logger.debug('Running coach login')
    username = request.form.get('username')
    password = request.form.get('password')

    # skip authentication if username or password is not set
    if not username or not password:
        flash(i18n.t('app.credentials_failed'), 'danger')
        return redirect(url_for('login_c'))

    # Conventus authentication
    r: LoginResult = conventus.coach_login(username, password, CONVENTUS_CLUB_NAME, request.headers)
    home_page = r.get('home_page')
    cookies = r.get('cookies')

    if r.get('login_success') and cookies is not None and home_page is not None:
        logger.info('Coach authenticated successfully')
        session.permanent = True  # persistent cookie lasting Flask's default 31 days
        session['username'] = username
        logger.trace(f'Added to session: {session["username"]}')
        session['PHPSESSID'] = cookies.get('PHPSESSID')
        logger.trace(f'Added to session: {session["PHPSESSID"]}')

        # fix teams, else use the teams from the homepage
        team_tds: ResultSet[Tag] = conventus.get_team_tds(home_page)
        logger.debug(f'Found {len(team_tds)} team tds')
        logger.trace(f'Team tds: {team_tds}')
        session['teams'] = conventus.extract_teams(team_tds)
        if not session['teams']:
            logger.warning(f'Coach {username} logged in with no teams assigned')
            flash(i18n.t('app.no_teams_assigned'), 'warning')
            session.pop('username', None)
            session.pop('teams', None)
            return redirect(url_for('login_c'))
        logger.trace(f'Added to session: {session["teams"]}')
        return redirect(url_for('main_menu', user=username))  # Redirect to the menu function and pass the username
    else:
        forwarded = request.headers.get('X-Forwarded-For', '')
        ip = forwarded.split(',')[0].strip() if forwarded else request.remote_addr
        logger.warning(f'Failed login attempt from ip: {ip}')
        flash(i18n.t('app.credentials_failed'), 'danger')
        return redirect(url_for('login_c'))


@app.route('/logout_c')
def logout_c():
    # session.clear() not used because the session id can be used for both member and coach in the same browser
    session.pop('teams', None)
    session.pop('username', None)
    session.pop('PHPSESSID', None)
    if session.get('username'):
        logger.warning('Coach logged out, but session still has username after clearing it')
    flash(i18n.t('app.logged_out'), 'success')
    return redirect(url_for('login_c'))


@app.route('/menu/<user>')
@require_session_keys('PHPSESSID', 'username', 'teams', redirect_to='login_c')
def main_menu(user: str) -> ResponseReturnValue:
    # user can only go to their own menu, not someone else's
    if session.get('username') != user:
        flash(i18n.t('app.viewing_your_own_menu'), 'info')
        user = session.get('username')

    # is there an active Conventus session?
    # make a test request to Conventus, and see if it works (e.g. by checking if the test page returned successfully
    # if not valid, flash message and redirect to login page
    s = set_session_cookie_for_requests()
    if not conventus.coach_login_check(s.cookies, request.headers):
        flash(i18n.t('app.no_active_session'), 'danger')
        return redirect(url_for('login_c'))  # Redirect to login if expired/no session

    # render main menu
    return render_template('main_menu.html', user=user)


@app.route('/notifications/<user>')
@require_session_keys('PHPSESSID', 'username', 'teams', redirect_to='login_c')
def notifications(user: str):
    logger.debug('Running notifications')
    # fb_notifications: list = get_fb_notifications(username=user, club_id=CONVENTUS_CLUB_ID)  # club_id=session.get('club_id')
    fb_notifications = get_notifications(username=user, club_id=CONVENTUS_CLUB_ID, service='facebook')
    service_name: str = 'Facebook'
    content: str = '<h3>' + i18n.t('app.service_notifications', service_name='Facebook') + '</h3>\n'
    if len(fb_notifications) > 0:
        logger.debug(f'service: {fb_notifications[0].service}')
        content += '            <p>' + i18n.t('app.notifications_linked_true', service_name='Facebook') + '</p><hr>\n'
        content += f'''            <h3>{i18n.t('app.manage_notifications', service_name='Facebook')}</h3>
            <form id="tg_update_form" action="{url_for('notification_update', user=user)}" method="POST">
'''
        teams = session.get('teams', [])
        for team in teams:
            team_id = team.get('id')
            checked = False
            if team_id in fb_notifications[0].team_ids:
                checked = True
            content += f'''                <input type="checkbox" id="fb_{team_id}" name="fb_{team_id}" value="{team_id}"{' checked' if checked else ''}>
                <label for="fb_{team_id}" onclick="$('fb_{team_id}').click();"> {team.get('ref')}</label><br>
'''
        content += f'''                <input type="hidden" id="fb_service" name="service" value="facebook">
                <br><input type="submit" id="fb_btn" value="{i18n.t('app.update')}" class="btn">
            </form><hr>
'''
        content += f'''            <h3>{i18n.t('app.delete_link', service_name='Facebook')}</h3>
            <form id="fb_unlink_form" action="{url_for('notification_unlink')}" method="POST">
                <input type="hidden" id="fb_username_2" name="username" value="{user}">
                <input type="hidden" id="fb_clubname_2" name="clubname" value="{CONVENTUS_CLUB_NAME}">
                <input type="hidden" id="fb_service_2" name="service" value="facebook">
                <input type="submit" id="fb_btn_2" value="{i18n.t('app.unlink')}" class="btn-orange">
            </form>
'''
        logger.debug(f'Teams in session: {teams}')
        if len(fb_notifications) > 1:
            logger.warning(
                f'Multiple {service_name} notifications found for {user} with club ID of {CONVENTUS_CLUB_ID}. Only ID {fb_notifications[0].id} was updated.'
            )
    else:
        content += (
            '            <p>'
            + i18n.t(
                'app.fb_notification_signup_start',
                eir_link='<a href="https://www.facebook.com/profile.php?id=61591084650947" target="_blank">Eir</a>',
            )
            + f"""</p>
            <form id="fb_link_form" action="{url_for('notification_link')}" method="POST">
                <label for="linking_code">{i18n.t('app.enter_code_')}</label>
                <input type="text" id="fb_linking_code" name="linking_code">
                <input type="hidden" id="fb_service_1" name="service" value="facebook">
                <input type="hidden" id="fb_lingua_1" name="lingua" value="{get_locale()}">
                <input type="submit" id="fb_btn_1" value="{i18n.t('app.link')}" class="btn">
            </form>"""
        )
    service_name: str = 'Telegram'
    tg_notifications = get_notifications(username=user, club_id=CONVENTUS_CLUB_ID, service='telegram')
    content += '            <hr>\n            <h3>' + i18n.t('app.service_notifications', service_name=service_name) + '</h3>\n'
    if len(tg_notifications) > 0:
        content += '            <p>' + i18n.t('app.notifications_linked_true', service_name=service_name) + '</p><hr>\n'
        content += f'''            <h3>{i18n.t('app.manage_notifications', service_name=service_name)}</h3>
            <form id="tg_update_form" action="{url_for('notification_update', user=user)}" method="POST">
'''
        teams = session.get('teams', [])
        for team in teams:
            team_id = team.get('id')
            checked = False
            if team_id in tg_notifications[0].team_ids:
                checked = True
            content += f'''                <input type="checkbox" id="tg_{team_id}" name="tg_{team_id}" value="{team_id}"{' checked' if checked else ''}>
                <label for="tg_{team_id}" onclick="$('tg_{team_id}').click();"> {team.get('ref')}</label><br>
'''
        content += f'''                <input type="hidden" id="tg_service" name="service" value="telegram">
                <br><input type="submit" id="tg_btn" value="{i18n.t('app.update')}" class="btn">
            </form><hr>
'''
        content += f'''            <h3>{i18n.t('app.delete_link', service_name=service_name)}</h3>
            <form id="tg_unlink_form" action="{url_for('notification_unlink')}" method="POST">
                <input type="hidden" id="tg_username_2" name="username" value="{user}">
                <input type="hidden" id="tg_clubname_2" name="clubname" value="{CONVENTUS_CLUB_NAME}">
                <input type="hidden" id="tg_service_2" name="service" value="telegram">
                <input type="submit" id="tg_btn_2" value="{i18n.t('app.unlink')}" class="btn-orange">
            </form>
'''
        logger.debug(f'Teams in session: {teams}')
        if len(tg_notifications) > 1:
            logger.warning(
                f'Multiple {service_name} notifications found for {user} with club ID of {CONVENTUS_CLUB_ID}. Only ID {tg_notifications[0].id} was updated.'
            )
    else:
        content += (
            '            <p>'
            + i18n.t('app.tg_notification_signup_start', eir_link='<a href="https://t.me/eir4c_bot?start=linkeir" target="_blank">Eir</a>')
            + f"""</p>
            <form id="tg_link_form" action="{url_for('notification_link')}" method="POST">
                <label for="linking_code">{i18n.t('app.enter_code_')}</label>
                <input type="text" id="linking_code" name="linking_code">
                <input type="hidden" id="tg_service_1" name="service" value="telegram">
                <input type="hidden" id="tg_lingua_1" name="lingua" value="{get_locale()}">
                <input type="submit" id="tg_btn_1" value="{i18n.t('app.link')}" class="btn">
            </form>"""
        )
    return render_template('notifications.html', user=user, content=content)


@app.route('/notification_update/<user>', methods=['POST'])
@require_session_keys('PHPSESSID', 'username', 'teams', redirect_to='login_c')
def notification_update(user: str):
    logger.info('Updating notifications started')
    service: str = request.form.get('service')
    if service:
        if service == 'facebook':
            svc = 'fb'
        elif service == 'telegram':
            svc = 'tg'
    logger.debug(f'Updating notifications for user: {user}, service: {service}, svc: {svc}')
    service_name = service.title()
    selected_team_ids: list[str] = [v for k, v in request.form.items() if k.startswith(f'{svc}_')]
    updated = update_teams_for_notifications(user, CONVENTUS_CLUB_ID, service, selected_team_ids)
    if updated:
        flash(i18n.t('app.success_notifications_updated', service_name=service_name), 'success')
    else:
        flash(i18n.t('app.error_notifications_updated', service_name=service_name), 'danger')

    # redirect back to the exact page the user came from
    # Fallback to 'home' if the referrer header is missing
    return redirect(request.referrer or url_for('home'))


@app.route('/notification_link', methods=['POST'])
@require_session_keys('PHPSESSID', 'username', 'teams', redirect_to='login_c')
def notification_link():
    logger.info('Linking started')
    # grab the submitted code from the form
    service: str = request.form.get('service')
    service_name: str = service.title()
    raw_code: str = request.form.get('linking_code')

    # strip absolutely ALL whitespace (spaces, tabs, newlines) using Regex
    code = re.sub(r'\s+', '', raw_code)

    if not code or len(code) != 6:
        flash(i18n.t('app.invalid_code'), 'danger')
        return redirect(request.referrer or url_for('home'))

    # get info from db about the code, and if valid, add to db for this user
    doc = models.PendingLink.objects(code=code, service=service).first()
    if not doc:
        docs = models.PendingLink.objects(service=service)
        logger.debug(f'Pending: {len(docs)}')
        for d in docs:
            logger.trace(d)
        flash(i18n.t('app.expired_code'), 'danger')
        return redirect(request.referrer or url_for('home'))

    # add all team ids for this user to the db, so they can get notifications for all their teams
    teams = session.get('teams') or []
    team_ids: list[str] = []
    for team in teams:
        team_id = team.get('id')
        if team_id:
            team_ids.append(team_id)

    lingua: str = request.form.get('lingua')
    if not lingua:
        lingua = get_locale()

    if doc.sid:
        success = setup_notification(
            sid=doc.sid, username=session.get('username'), club_id=CONVENTUS_CLUB_ID, team_ids=team_ids, service=service, lingua=lingua
        )  # club_id=session.get('club_id')
    if not success:
        flash(i18n.t('app.notification_setup_failed', service_name=service_name), 'danger')
        return redirect(request.referrer or url_for('home'))

    # create the success notifications
    if service == 'facebook':
        send_fb_messenger_response(
            doc.sid, i18n.t('app.notifications_linked', name=doc.name, club_name=CONVENTUS_CLUB_NAME, service_name=service_name)
        )
    else:
        send_telegram_message(doc.sid, i18n.t('app.notifications_linked', name=doc.name, club_name=CONVENTUS_CLUB_NAME, service_name=service_name))
    flash(i18n.t('app.success_notifications_linked', service_name=service_name), 'success')

    # delete the pending link from the database
    doc.delete()

    # redirect back to the exact page the user came from
    # Fallback to 'home' if the referrer header is missing
    return redirect(request.referrer or url_for('home'))


@app.route('/notification_unlink', methods=['POST'])
@require_session_keys('PHPSESSID', 'username', 'teams', redirect_to='login_c')
def notification_unlink():
    club_id: str = CONVENTUS_CLUB_ID
    service = request.form.get('service')
    service_name = service.title()
    username = session.get('username')
    unique_sids = []
    deleted_count = 0
    if username:
        # docs = get_fb_notifications(username, club_id)
        # docs = get_notifications(username, club_id, 'telegram')
        docs = get_notifications(username, club_id, service)
        deleted_count = delete_link_for_coach(username=username, club_id=club_id, service=service)
        for doc in docs:
            if doc.sid and doc.sid not in unique_sids:
                unique_sids.append(doc.sid)
                notify_coach(doc, i18n.t('app.notifications_unlinked', service_name=service_name, club_name=CONVENTUS_CLUB_NAME, locale=doc.lingua))
    if deleted_count and len(unique_sids) > 0:
        flash(i18n.t('app.success_notifications_unlinked', service_name=service_name), 'success')
    else:
        flash(i18n.t('app.error_notifications_unlinked', service_name=service_name), 'danger')
    return redirect(request.referrer or url_for('home'))


@app.route('/member_updates/<user>')
@require_session_keys('PHPSESSID', 'username', 'teams', redirect_to='login_c')
def member_updates(user: str) -> ResponseReturnValue:
    """
    Lookup member updates for the teams in the session. If no teams are in the session, it will attempt to read the home page and extract the teams.
    """
    logger.debug('Running member_updates')
    s = set_session_cookie_for_requests()

    if not session.get('teams'):
        # read home page and check for changes in team members
        username = session.get('username')
        if username and session.get('PHPSESSID'):
            admin_username = os.environ.get('ADMIN')
            if admin_username and username == admin_username:
                # get all teams in dept for admin user
                logger.info('Admin user detected')
                content = conventus.read_checkin_list_start_page(request.headers, s.cookies)
                logger.trace(content)
                session['teams'] = conventus.parse_checkin_list_start_page(content)
            else:
                home_page = conventus.get_home_page(s.cookies, request.headers)
                team_tds: ResultSet[Tag] = conventus.get_team_tds(home_page)
                logger.debug(f'Found {len(team_tds)} team tds')
                logger.trace(f'Team tds: {team_tds}')
                session['teams'] = team_tds

    content = ''
    if session.get('teams'):
        logger.debug(f'Teams in session: {session.get("teams")}')
        send_notifications: int = 0
        if request.args.get('notify'):
            send_notifications = int(request.args.get('notify'))
        content = conventus.check_for_added_and_removed_members_by_teams(
            session.get('teams'), headers=request.headers, cookies=s.cookies, group_results=True, send_notifications=send_notifications
        )
    else:
        flash(i18n.t('app.site_error'), 'danger')
        return redirect(url_for('main_menu', user=user))
    return render_template('member_updates.html', user=user, content=content)


def team_menu_logic() -> tuple:
    # display "team", e.g. Hold 65 (or paired name, e.g. Hold 31 & 32) for coaches
    teams = session.get('teams', [])
    logger.debug(f'Received from session: {teams}')
    date = datetime.now().strftime('%Y-%m-%d')
    team_refs_after_pairing = []
    for t in teams:
        logger.debug(f'Processing team: {t}')
        ref = get_pairing(t)
        if ref is None:
            ref = t.get('ref')
        if ref not in team_refs_after_pairing:
            team_refs_after_pairing.append(ref)
        if t.get('ref') != ref:
            logger.debug(f'Team {t.get("ref")} is paired as {ref}')
    return team_refs_after_pairing, date


@app.route('/checkin/<user>')
@require_session_keys('PHPSESSID', 'username', 'teams', redirect_to='login_c')
def checkin_menu(user: str) -> ResponseReturnValue:
    teams = session.get('teams', [])
    logger.debug(f'Received from session: {teams}')
    team_refs_ap, date = team_menu_logic()
    logger.debug(f'Received from team_menu_logic: {team_refs_ap}')
    return render_template('checkin_menu.html', user=user, teams=team_refs_ap, date=date)


@app.route('/checkin/<team_name>/<date>/<user>')
@require_session_keys('PHPSESSID', 'username', 'teams', redirect_to='login_c')
def checkin_team(team_name: str, date: str, user: str) -> ResponseReturnValue:
    logger.debug('Team check-in')
    content = ''
    try:
        team_id = team_ref_to_id(team_name)
        logger.debug(team_id)
        s = set_session_cookie_for_requests()
        logger.trace(s.cookies)

        # get team lists for the date
        all_team_content: list = []
        for team_id in team_id.split(','):
            # r: RequestsResponse = conventus.get_team_checkin_lists(team_id, s.cookies, request.headers)
            r: requests.Response = conventus.get_team_checkin_lists(team_id, s.cookies, request.headers)
            list_id: str = conventus.find_team_checkin_list_id_from_content(team_id, date, r.content)
            logger.debug(f'list ID: {list_id}')
            if list_id == '':
                # no list exists, create new list for the team and date, then get the new list id
                logger.debug(f'Creating new check-in list for {team_name} (id: {team_id}) on {date}')
                list_id = conventus.add_checkin_list(s.cookies, team_id, date, request.headers)
            if list_id:
                checkin_list_content: str = conventus.get_checkin_list(s.cookies, team_id, date, list_id, request.headers)
                logger.debug('start find_member_checkins')
                member_checkins: list[dict] = conventus.find_member_checkins(team_id, date, checkin_list_content)
                logger.debug('end find_member_checkins')
                if len(member_checkins) and member_checkins[0] == {'db_available': False}:
                    member_checkins.pop(0)
                    flash(i18n.t('app.signout_db_unavailable'), 'danger')
                logger.trace(f'Check-ins: {member_checkins}')
                team_content = ''
                for ci in member_checkins:
                    # {'member_id': member_id, 'member_name': member_name_norm, 'status': status}
                    # <input type="checkbox" id="ci_nnnnnnn" name="ci_nnnnnnn" value="nnnnnnn" onclick="member_clicked(nnnnnnn, 2, list_id);">
                    checked = ''
                    info = ''
                    member_id = ci.get('member_id')
                    status = ci.get('status', '')
                    if status == 'checked-in':
                        checked = ' checked'
                    elif status == i18n.t('app.checked_in'):
                        checked = ' checked'
                    if 'signed-out' in status:
                        status = status.replace('signed-out', i18n.t('app.signed_out'))  # l10n
                        info = f': <span style="color: red" id="so_{member_id}">{status}</span>'
                    elif status == i18n.t('app.signed_out'):
                        info = f': <span style="color: red" id="so_{member_id}">{status}</span>'
                    team_content += f'''<input type="checkbox" id="ci_{member_id}" name="ci_{member_id}" value="{member_id}"{checked} onclick="member_clicked({member_id}, 2, {list_id});">
                    <label for="ci_{member_id}" onclick="$('ci_{member_id}').click();"> {ci.get('member_name')}{info}</label><br>
                    '''
                if team_content:
                    team_content = f'<p>{team_content}</p>'
                all_team_content.append(team_content)
        if all_team_content:
            content = '<hr />'.join(all_team_content)
    except SessionError:
        logger.debug(f'Session {session.get("teams")}')
        flash(i18n.t('app.session_error'), 'danger')
        return redirect(url_for('checkin_menu', user=user))
    except SiteError as e:
        flash(f'{i18n.t("app.site_error")} ({e})', 'danger')
        return redirect(url_for('checkin_menu', user=user))
    except ParsingError:
        flash(i18n.t('app.parsing_error'), 'danger')
        return redirect(url_for('checkin_menu', user=user))
    return render_template('checkin_team.html', user=user, team=team_name, date=date, content=content)


@app.route('/signouts/<user>')
@require_session_keys('PHPSESSID', 'username', 'teams', redirect_to='login_c')
def signouts_menu(user) -> str:
    team_refs, date = team_menu_logic()
    return render_template('signouts_menu.html', user=user, teams=team_refs, date=date)


@app.route('/signouts/<team_name>/<date>/<user>')
@require_session_keys('PHPSESSID', 'username', 'teams', redirect_to='login_c')
def view_signouts(team_name, date, user) -> ResponseReturnValue:
    content = ''
    try:
        # team = get_paired_team_info(team_name)
        team_id = team_ref_to_id(team_name)
        logger.debug(f'{team_name}: {team_id}')
        s = set_session_cookie_for_requests()
        logger.trace(s.cookies)
        # get team lists for the date
        content = ''
        # connect_to_db('signouts')

        for team_id in team_id.split(','):
            content += '</p><hr><p>' if content else ''
            dept_id = CONVENTUS_DEPT_ID.split('_')[-1]

            # member_signouts is a list of Signout.object with "member_id" and "reason"
            member_signouts: list[models.Signout] = get_signout_list_from_db(date, CONVENTUS_CLUB_ID, dept_id, team_id)
            r = conventus.get_team_checkin_lists(team_id, s.cookies)
            logger.trace(r.content)
            list_id = conventus.find_team_checkin_list_id_from_content(team_id, date, r.content)
            logger.debug(f'List id: {list_id}')
            if list_id:
                checkin_list_content: str = conventus.get_checkin_list(s.cookies, team_id, date, list_id)
                member_checkins: list = conventus.find_member_checkins(team_id, date, checkin_list_content, member_signouts)
                logger.debug(f'Check-ins: {len(member_checkins)}')
                for ci in member_checkins:
                    # {'member_id': member_id, 'member_name': member_name_norm, 'status': status}
                    logger.trace(f'Check-in data: {ci}')
                    status = ci.get('status', '')
                    member_id = ci.get('member_id', '')
                    checked = ''
                    if status == 'checked-in':
                        checked = ' checked'
                    if 'signed-out' in status:
                        status = status.replace('signed-out', i18n.t('app.signed_out')).replace('other:', i18n.t('app.other_'))  # l10n
                        content += f'<input type="checkbox" id="ci_{member_id}" value="{member_id}"{checked} disabled><label for="ci_{member_id}"> {ci.get("member_name")}: <span style="color: red">{status}</span></label><br>'
                    else:
                        status = status.replace('checked-in', i18n.t('app.checked_in'))
                        content += f'<input type="checkbox" id="ci_{member_id}" value="{member_id}"{checked} disabled><label for="ci_{member_id}"> {ci.get("member_name")}</label><br>'
            else:
                # get team list with member_name and member_id
                team_ref_unpaired = team_id_to_ref(team_id, 'teams')
                csv_text: str = conventus.download_csv(s.cookies, f'g_{team_id}', team_ref_unpaired)
                if not csv_text:
                    flash(i18n.t('app.error_downloading_team_list'), 'danger')
                    return redirect(url_for('signouts_menu', user=user))
                else:
                    logger.trace(csv_text)
                    team_members = conventus.get_members_from_csv(csv_text)
                    logger.trace(f'Team members: {team_members}')
                    for ms in member_signouts:
                        logger.debug(f'{team_id} signout: {ms}')
                        # team_members is a list of dict with "ID" and "navn" as keys
                        for tm in team_members:
                            logger.debug(f'Team member info: {tm}')
                            if ms.member_id == tm.get('ID'):
                                # team member matched signout, add to message, then go to next signout
                                reason_l10n = localize_reason(ms.reason)
                                # html = f'{tm.get("Navn")}: <span style="color: red">{i18n.t("app.signed_out")} ({ms.reason.replace("other:", i18n.t("app.other_"))})</span><br>'  # l10n
                                html = f'{tm.get("Navn")}: <span style="color: red" id="so_{ms.member_id}">{i18n.t("app.signed_out")} ({reason_l10n})</span><br>'  # l10n: NB: ms.reason is already localized
                                content += html
                                break
        if content:
            content = f'<p>{content}</p><hr>'
            content = content.removesuffix('<p></p><hr>')  # remove empty team (paired team has sign-outs for first team but not second one)
    except DatabaseError:
        flash(i18n.t('app.db_error_msg'), 'danger')
        return redirect(url_for('signouts_menu', user=user))
    except SessionError:
        flash(i18n.t('app.session_error') + f'<br>Teams: {session.get("teams")}', 'danger')
        return redirect(url_for('signouts_menu', user=user))
    except SiteError:
        flash(i18n.t('app.site_error'), 'danger')
        return redirect(url_for('signouts_menu', user=user))
    except ParsingError:
        flash(i18n.t('app.parsing_error'), 'danger')
        return redirect(url_for('signouts_menu', user=user))
    # finally:
    #    disconnect(alias='signouts')

    if content == '':
        # convert date to locale based date
        localized_date = date
        if get_locale() == 'da':
            localized_date = date_std_to_da(date)
        content = f'<p>{i18n.t("app.no_signouts", team_name=team_name, date=localized_date)}</p><hr>'

    # page should also show buttons to go back to the sign-out menu, go to the check-in menu, go back to the main menu
    return render_template('signouts_team.html', user=user, team=team_name, date=date, content=content)


@app.route('/boxcheck', methods=['POST', 'OPTIONS'])
@require_session_keys('PHPSESSID', 'username', 'teams', redirect_to='login_c')
def boxcheck() -> ResponseReturnValue:
    """Get around js security when setting the checkbox value in Conventus"""
    origin: str = request.headers.get('Origin', '')
    logger.debug(f'boxcheck request from origin: {origin}')
    my_app = False
    if 'http://localhost' == origin or '/localhost:' in origin or '127.0.0.1' in origin or 'eir-qkcv.onrender.com' in origin:
        my_app = True

    # Handle the CORS pre-flight handshake
    if request.method == 'OPTIONS':
        res = make_response()
        if my_app:
            res.headers['Access-Control-Allow-Origin'] = origin
            res.headers['Access-Control-Allow-Methods'] = 'POST, OPTIONS'
            res.headers['Access-Control-Allow-Headers'] = 'Content-Type'
        return res

    # Logic for the actual POST
    if my_app:
        phpsessid = session.get('PHPSESSID')
        logger.trace(f'sessid: {phpsessid}')
        real_response_text = ''
        try:
            real_response_text = conventus.passthru_check_action(request, phpsessid)
            # real_response_text = conventus.passthru_check_action_fake(request)
        except Exception as e:
            logger.exception(f'Failed to set checkbox: {e}')
            real_response_text = 'fail'
        logger.trace(f'response from conventus: {real_response_text}')

        # Respond back to our JavaScript
        res = make_response(real_response_text)
        res.headers['Access-Control-Allow-Origin'] = origin
        return res

    return make_response('fail', 403)


def team_id_to_ref(team_id: str, session_key: str) -> str:
    """Convert team_id to team_ref using the teams stored in the session. NB: Requires the session key because it is used by both coach and member."""
    teams: list = session.get(session_key, [])
    for t in teams:
        logger.debug(f'team_id_to_ref processing team: {t}')
        if t.get('id') == team_id:
            ref = t.get('ref')
            # handle cases where the session data is not as expected
            if not ref:
                logger.error(f'Team ref not found for Team ID: {team_id}')
                raise SessionError(f'Team ref not found for Team ID: {team_id}')
            if type(ref) is not str:
                logger.error(f'Unexpected type for Team ref: {type(ref)}')
                raise SessionError(f'Unexpected type for Team ref: {type(ref)}')
            return ref
    logger.error('Team ID not in session teams')
    raise SessionError('Team ID not in session teams')


def team_ref_to_id(ref: str, session_key: str = 'teams') -> str:
    """Convert team_ref to team_id using the teams stored in the session"""
    teams: list = session.get(session_key, [])
    # from teams find team id from team name (passed as team)
    team_id = None
    for t in teams:
        logger.debug(f'team_ref_to_id processing team: {t}')
        if t.get('ref') == ref:
            team_id = t.get('id')
            # handle cases where the session data is not as expected
            if not team_id:
                logger.error(f'Team ID not found for {ref}')
                raise SessionError(f'Team ID not found for {ref}')
            if type(team_id) is not str:
                logger.error(f'Unexpected type for Team ID: {type(team_id)}')
                raise SessionError(f'Unexpected type for Team ID: {type(team_id)}')
            return team_id
    paired_teams: list[dict] = PAIRED_TEAMS  # later change to DB call
    for p in paired_teams:
        if p.get('name') == ref:
            team_id = get_paired_team_ids(ref, paired_teams)
            if not team_id:
                logger.error(f'Team IDs not found for {ref}')
                raise SessionError(f'Team ID not found for {ref}')
            if type(team_id) is not str:
                logger.error(f'Unexpected type for Team ID: {type(team_id)}')
                raise SessionError(f'Unexpected type for Team ID: {type(team_id)}')
            return team_id
    logger.error(f'Team ref {ref} not in session teams or paired teams')
    raise SessionError(f'Team ref {ref} not in session teams or paired teams')


# member
@app.route('/member')
def login_m() -> ResponseReturnValue:
    if request.headers.get('Referer'):
        logger.debug(f'Referer header: {request.headers.get("Referer")}')
    logger.trace('Rendering member login page')
    return render_template('member_login.html')


def team_menu_logic_member() -> tuple:
    # display "team_name", e.g. "Hold XX - Trampolin - Begynder / Øvet fra skolestart" for members
    teams = session.get('member_teams', [])
    logger.debug(f'Received from session: {teams}')
    date = datetime.now().strftime('%Y-%m-%d')
    team_names = []
    for t in teams:
        logger.debug(
            f'Processing team: {t}'
        )  # {'team_name': 'Hold XX - Trampolin - Begynder / Øvet fra skolestart', 'id': '000000', 'ref': 'Hold XX'}
        team_name = t.get('team_name')
        team_names.append(team_name)
    return team_names, date


@app.route('/member_login_go', methods=['POST'])
def member_login() -> ResponseReturnValue:
    login_type = request.form.get('log_ind_med')
    phone_country = request.form.get('mobil_land')
    phone_no = request.form.get('mobil')
    email = request.form.get('email')
    password = request.form.get('password')
    club_id = CONVENTUS_CLUB_ID

    if login_type == 'mobil':
        if not phone_no or not password:
            logger.warning(f'Invalid parameters for {login_type}: {phone_no}')
            flash(i18n.t('app.member_credentials_failed', login_type=login_type), 'danger')
            return redirect(url_for('login_m'))
    else:
        if not email or not password:
            logger.warning(f'Invalid parameters for {login_type}: {email}')
            flash(i18n.t('app.member_credentials_failed', login_type=login_type), 'danger')
            return redirect(url_for('login_m'))

    cookies, selectable_profiles, login_success = conventus.member_login(
        password, club_id, login_type, request.headers, email, phone_country, phone_no, session.get('member_sessid')
    )
    session.permanent = True  # persistent cookie lasting Flask's default 31 days
    logger.debug(f'Selectable profiles: {selectable_profiles} ({len(selectable_profiles)})')
    logger.debug(f'Login successful: {login_success}')
    if login_success and len(selectable_profiles) == 1:
        # set user session
        # session['selectable_profiles'] = selectable_profiles  # uncomment and then login to use for testing
        logger.debug(f'Profile: {selectable_profiles[0]}')
        session['member_sessid'] = cookies.get('PHPSESSID')
        session['club_id'] = club_id
        logger.debug(f'Added to session: club_id: {session["club_id"]}')
        member_id: str = selectable_profiles[0].get('member_id')
        session['member_id'] = member_id
        logger.debug(f'Added to session: member_id: {session["member_id"]}')
        name: str = selectable_profiles[0].get('name')
        session['name'] = name
        session['member_teams'] = selectable_profiles[0].get('teams')
        logger.debug(f'Added to session: member_teams: {session["member_teams"]}')
        logger.info('redirect to member_menu')
        return redirect(url_for('member_menu'))  # Redirect to the menu function
    elif login_success and selectable_profiles:
        # set user session
        session['member_sessid'] = cookies.get('PHPSESSID')
        session['club_id'] = club_id
        logger.debug(f'Added to session: {session["club_id"]}')
        session['selectable_profiles'] = selectable_profiles
        logger.debug(f'Added to session: {session["selectable_profiles"]}')
        logger.info('redirect to member_profile_select')
        return redirect(url_for('member_profile_select'))
    elif login_success:
        # logged in to conventus, but no members of the login are a current team member of a valid team
        # session.clear() not used because the session id can be used for both member and coach in the same browser
        session.pop('member_teams', None)
        session.pop('member_id', None)
        session.pop('club_id', None)
        session.pop('name', None)
        session.pop('selectable_profiles', None)
        logger.warning('Login successful, but no team members in valid "depts" found in any profile')
        flash(i18n.t('app.no_profiles'), 'danger')
        return redirect(url_for('login_m'))
    else:
        # TODO anonymize logging of failed login attempts
        logger.warning(f'Failed login attempt for {login_type}: {phone_no if login_type == "mobil" else email}')
        flash(i18n.t('app.member_credentials_failed', login_type=login_type), 'danger')
        return redirect(url_for('login_m'))


@app.route('/member_profile_select')
@require_session_keys('member_sessid', 'selectable_profiles', redirect_to='login_m')
def member_profile_select() -> ResponseReturnValue:
    content = '                    <table border="0" cellpadding="2" cellspacing="0" width="100%" class="bt" style="color: #000000;">'
    for profile in session.get('selectable_profiles', []):
        member_id = profile.get('member_id')
        name = profile.get('name')
        content += f"""                        <tr><td onMouseOver="this.style.cursor='pointer';" onMouseOut="this.style.cursor='';" onClick="location.href='{url_for('member_menu', member_id=member_id)}';"><img src="/static/medlem.bmp" border="0" style="margin-bottom: -3px;" />{name}</td></tr>"""

    content += '                    </table>'
    return render_template('member_profile_select.html', content=content)


@app.route('/logout_m')
def logout_m():
    # session.clear() not used because the session id can be used for both member and coach in the same browser
    session.pop('member_teams', None)
    session.pop('member_id', None)
    session.pop('member_sessid', None)
    session.pop('club_id', None)
    session.pop('name', None)
    session.pop('selectable_profiles', None)
    flash(i18n.t('app.logged_out'), 'success')
    return redirect(url_for('login_m'))


@app.route('/member_menu')
@require_session_keys('member_sessid', 'name', redirect_to='login_m')
def member_menu() -> ResponseReturnValue:
    logger.info('setting up member_menu')
    member_id: str | None = session.get('member_id')
    if not member_id:
        member_id = request.args.get('member_id')
    if not member_id:
        flash(i18n.t('app.no_active_session_for_member'), 'info')
        return redirect(url_for('logout_m'))

    # use session name if it is set, otherwise get it from selectable_profiles (e.g. when coming from profile select page)
    name = session.get('name')

    switchable = bool(len(session.get('selectable_profiles', [])) > 1)
    if switchable:
        logger.debug('getting info from selectable_profiles in session')
        logger.debug(session.get('selectable_profiles', []))
        for profile in session.get('selectable_profiles', []):
            logger.trace(profile)
            if member_id == profile.get('member_id', ''):
                session['member_id'] = member_id
                logger.debug(f'Added to session: {session["member_id"]}')
                name = profile.get('name')
                session['name'] = name
                logger.debug(f'Added to session: {session["name"]}')
                session['member_teams'] = profile.get('teams')

                logger.debug(f'Added to session: member_teams: {session["member_teams"]}')
                # session['profile'] = profile
                # logger.debug(f'Added to session: {session["profile"]}')
                break

    date = datetime.now().strftime('%Y-%m-%d')

    # if link is from another member, or if something goes wrong and the member info never gets set in the session,
    # the member will be logged out
    if session.get('member_id') != member_id:
        flash(i18n.t('app.no_active_session_for_member'), 'info')
        return redirect(url_for('logout_m'))

    for team in session.get('member_teams'):
        team_id = team.get('id')
        logger.debug(f'Processing team: {team.get("team_name")} (id: {team_id})')
        # if team is not stored in the db, then store it
        if not get_team_info_from_db(team_id=team_id):
            logger.debug(f'Team {team.get("team_name")} (id: {team_id}) not found in DB, fetching info from team page')
            team_info: dict[str, datetime | str | bool] = {}
            try:
                content = conventus.get_member_team_info_page(team_id, request.headers, {'PHPSESSID': session.get('member_sessid')})
                team_info = conventus.parse_member_team_info_page(content)
                team_info['team_id'] = team.get('id')
                team_info['ref'] = team.get('ref')
                team_info['name'] = team.get('team_name')
                team_info['club_id'] = session.get('club_id')
                team_info.pop('active', None)
            except ParsingError:
                logger.error(f'Failed to parse member team info for team_id: {team_id}')
                flash(i18n.t('app.cannot_fetch_team_info', team=team.get('ref')), 'danger')
                # TODO send message to admin
            except SiteError:
                logger.error(f'Failed to fetch member team info page for team_id: {team_id}')
                flash(i18n.t('app.cannot_fetch_team_info', team=team.get('ref')), 'danger')
                # TODO send message to admin
            except SessionError:
                logger.error(f'Failed to fetch member team info page for team_id: {team_id}')
                flash(i18n.t('app.cannot_fetch_team_info', team=team.get('ref')), 'danger')
                # TODO send message to admin

            if team_info:
                try:
                    add_team_info_to_db(team_info)
                except DatabaseError:
                    flash(i18n.t('app.cannot_fetch_team_info', team=team.get('ref')), 'danger')
                    # TODO send message to admin
    return render_template('member_menu.html', member_id=member_id, name=name, date=date, switchable=switchable)


def normalize_date(d) -> str:
    return d.strftime('%Y-%m-%d') if isinstance(d, datetime) else str(d)


@app.route('/member_signout/<date>')
@require_session_keys('member_id', 'member_teams', redirect_to='login_m')
def member_signout(date: str) -> ResponseReturnValue:
    member_id: str = session.get('member_id')

    # get signouts from DB with selected date or later
    dept_id = CONVENTUS_DEPT_ID.split('_')[-1]  # TODO: get dept_id from session
    club_id = CONVENTUS_CLUB_ID  # TODO: get dept_id from session session.get('club_id')
    logger.debug(f'Dept ID from session: {session.get("dept_id")}')
    logger.debug(f'Dept ID from config:  {dept_id}')
    logger.debug(f'Club ID from session: {session.get("club_id", "")}')
    logger.debug(f'Club ID from config:  {club_id}')
    if club_id is None:
        logger.error('Club ID not found in session')
        flash(i18n.t('app.no_active_session_for_member'), 'danger')
        return redirect(url_for('login_m'))

    # get teams stored in session
    teams: TeamData = session.get('member_teams', [])
    logger.debug(f'Teams from session: {teams}')

    # get member signouts
    current_date: str = datetime.now().strftime('%Y-%m-%d')
    existing_signouts: list[models.Signout] = get_member_signouts_from_db(member_id, current_date, club_id=club_id, dept_id=dept_id)
    logger.debug(f'Number of existing signouts: {len(existing_signouts)}')

    # generate the form inputs, other than the date (which is in the template)
    signup_content: str = ''
    signout_content: str = ''

    # Filter/normalize once, up front
    relevant_signouts = [
        (so, normalize_date(so.date))  # 3. build this tuple and add it to the list
        for so in existing_signouts  # 1. Loop over every signout
        if normalize_date(so.date) >= current_date  # 2. keep only the ones passing this check
    ]

    team_ids_with_signout = set()

    for team in teams:
        for so, so_date in relevant_signouts:
            logger.trace(f'Signout: {so.to_mongo().to_dict()}')
            if so.team_id != team['id']:
                continue
            signup_content += f'\n                        <option value="{so.id}">{so_date} {team.get("team_name")}</option>'
            if so_date == date:
                team_ids_with_signout.add(team['id'])

    for team in teams:
        if team['id'] not in team_ids_with_signout:
            signout_content += f'\n                        <option value="{team["id"]}">{team.get("team_name")}</option>'

    if signout_content:
        signout_content = f"""<label for="team_id">{i18n.t('app.select_team')}</label>
                    <select id="team_id" name="team_id">{signout_content}
                    </select><br /><br />
                    <label for="reason">{i18n.t('app.reason_')}</label>&nbsp;
                    <select id="reason" name="reason" required>
                        <option value="">{i18n.t('app.select')}</option>
                        <option value="sick">{i18n.t('app.sick')}</option>
                        <option value="injured">{i18n.t('app.injured')}</option>
                        <option value="vacation">{i18n.t('app.vacation')}</option>
                        <option value="school">{i18n.t('app.school')}</option>
                        <option value="work">{i18n.t('app.work')}</option>
                        <option value="sport">{i18n.t('app.sport')}</option>
                        <option value="other">{i18n.t('app.other')}</option>
                    </select>&nbsp;
                    <input type="text" id="additional_reason" name="additional_reason" placeholder="{i18n.t('app.add_comment')}" style="width:55%" required>
                    <input type="hidden" name="member_id" id="member_id" value="{member_id}"><br /><br />
                    <button id="signout-button" type="button">{i18n.t('app.sign_out')}</button>"""
    else:
        signout_content = f'<p>{i18n.t("app.no_teams_available_for_signout")}</p>'
    if signup_content:
        signup_content = f"""<p>{i18n.t('app.signups_possible')}</p>
                    <select id="existing_signouts" name="existing_signouts">{signup_content}
                    </select><br /><br />
                    <!--<input type="hidden" name="team_id" id="team_id" value="{so.team_id}"><br /><br />
                    <input type="hidden" name="member_id" id="member_id" value="{member_id}"><br /><br />-->
                    <button id="signup-button" type="button">{i18n.t('app.sign_up')}</button>"""
    return render_template(
        'member_signout.html', member_id=member_id, date=date, content=signout_content, content_in=signup_content, current_date=current_date
    )


@app.route('/signout_go', methods=['POST'])
@require_session_keys('name', 'member_id', 'member_teams', redirect_to='login_m')
def signout_go() -> ResponseReturnValue:
    name: str = session.get('name')
    member_id: str = request.form.get('member_id')
    team_id: str = request.form.get('team_id')

    # if session.get('member_id') != member_id or team_id not in session.get('member_teams'):
    if session.get('member_id') != member_id:
        logger.error(
            f"Signout stopped because member_id for the signout ({member_id}) doesn't match the current member_id ({session.get('member_id')})"
        )
        flash(i18n.t('app.signout_failed'), 'danger')
        return 'fail'

    logger.debug(f'Signout request for member_id: {member_id}, team_id: {team_id}, dept_id: {request.form.get("dept_id")}')
    dept_id = request.form.get('dept_id') or CONVENTUS_DEPT_ID.split('_')[-1]  # TODO: get dept_id from form
    club_id = CONVENTUS_CLUB_ID  # TODO: get club_id from session session.get('club_id')
    signout_date = request.form.get('date')
    existing_signups: list[models.Signout] = get_member_signouts_from_db(
        member_id, signout_date, club_id=club_id, dept_id=dept_id, team_id=team_id, status=False
    )
    for signup in existing_signups:
        signup.delete()  # delete existing signups so we only have one signup/out record for the event

    # add signout to the database
    result: models.Signout = add_signout_to_db(
        request.form.get('date'),
        member_id,
        club_id,
        dept_id,
        team_id,
        name,
        True,
        request.form.get('reason'),
        request.form.get('additional_reason'),
    )
    if result is None:
        flash(i18n.t('app.signout_failed'), 'danger')
        return 'fail'

    da_date = date_std_to_da(request.form.get('date'))
    team_ref = team_id_to_ref(team_id, 'member_teams')
    flash(i18n.t('app.signout_success_team_date', team=team_ref, date=da_date), 'success')

    try:
        # query the database for the coach's service ID and send a notification
        coaches = get_coaches_to_notify(team_id)
        total_coaches = len(coaches)
        notification_successes = 0
        for coach in coaches:
            comment = i18n.t(f'app.{request.form.get("reason")}', locale=coach.lingua)
            if request.form.get('additional_reason'):
                comment += ' - ' + request.form.get('additional_reason')
            event_type_l10n = i18n.t('app.practice', locale=coach.lingua)
            notification_successes += notify_coach2(
                coach,
                notification_text=i18n.t(
                    'app.signout_notification',
                    name=name,
                    event_type=event_type_l10n,
                    team_or_event=team_ref,
                    date=da_date,
                    comment=comment,
                    locale=coach.lingua,
                ),
                action='signout',
                name=name,
                event_type_l10n=event_type_l10n,
                team_or_event=team_ref,
                date=da_date,
                comment=comment,
            )

        if total_coaches and total_coaches == notification_successes:
            logger.info(f'All coach notifications ({total_coaches}) sent successfully.')
        if total_coaches and notification_successes < total_coaches:
            logger.error(f'Coach notifications successful: {notification_successes} of {total_coaches}.')
            raise Exception(f'Failed to send {total_coaches - notification_successes} of {total_coaches} notifications.')
    except Exception as e:
        logger.error(f'Error occurred while notifying coaches (signout): {e}')
        # TODO send ticket to admin, for now coaches should check their sign-outs in Conventus
        # flash(i18n.t('app.notification_error'), 'danger')
        # return 'fail'
    return 'success'


@app.route('/signup_go', methods=['POST'])
@require_session_keys('member_id', 'member_teams', redirect_to='login_m')
def signup_go() -> ResponseReturnValue:
    name: str | None = session.get('name')
    if not name:
        flash(i18n.t('app.session_expired'), 'danger')
        return redirect(url_for('login_m'))

    signout_id: str = request.form.get('signout_id')
    logger.debug(f'received signout_id: {signout_id}')

    result = None
    result: models.Signout | None = update_signout_by_id(signout_id, name)
    if result is None:
        flash(i18n.t('app.signup_failed'), 'danger')
        return 'fail'
    logger.debug(f'Result: {result.to_mongo().to_dict()}')
    team_id = result.team_id
    clean_date: str = result.date.strftime('%Y-%m-%d') if isinstance(result.date, datetime) else str(result.date)
    da_date = date_std_to_da(clean_date)
    logger.debug(da_date)
    logger.debug(team_id)
    team_ref = team_id_to_ref(team_id, 'member_teams')
    flash(i18n.t('app.signup_success_team_date', team=team_ref, date=da_date), 'success')
    try:
        # query the database for the coach information to send a notification
        coach_notifications = get_coaches_to_notify(team_id)
        total_coach_notifications = len(coach_notifications)
        notification_successes = 0
        for coach in coach_notifications:
            event_type_l10n = i18n.t(
                'app.practice', locale=coach.lingua
            )  # TODO fix this so that a practice is stored in the DB as an event type of "practice"
            # passing the coach uses the service and service ID (sid)
            notification_successes += notify_coach2(
                coach,
                notification_text=i18n.t(
                    'app.signup_notification', name=name, event_type=event_type_l10n, team_or_event=team_ref, date=da_date, locale=coach.lingua
                ),
                action='signup',
                name=name,
                event_type_l10n=event_type_l10n,
                team_or_event=team_ref,
                date=da_date,
            )

        if total_coach_notifications and total_coach_notifications == notification_successes:
            logger.info(f'All coach notifications ({total_coach_notifications}) sent successfully.')
        if total_coach_notifications and notification_successes < total_coach_notifications:
            logger.error(f'Coach notifications successful: {notification_successes} of {total_coach_notifications}.')
            raise NotificationError(
                f'Failed to send {total_coach_notifications - notification_successes} of {total_coach_notifications} notifications.'
            )
    except NotificationError as e:
        logger.error(f'Error occurred while notifying coaches (signup_go): {e}')
        # TODO send ticket to admin, for now coaches should check their sign-outs/ups in Eir
    return 'success'


# other
def set_session_cookie_for_requests(sessid: str | None = None):
    s = requests.session()
    if sessid is None:
        sessid = session.get('PHPSESSID')
    s.cookies.set('PHPSESSID', sessid, domain='conventus.dk')
    return s


def notify_coach(coach, notification_text: str) -> int:
    r: bool = False
    if coach.service == 'facebook':
        try:
            # r = send_fb_messenger_account_update(coach.sid, notification_text)
            r = send_fb_messenger_response(coach.sid, notification_text)
        except MessengerError as e:
            logger.error(f'Error occurred while sending FB Messenger message to PSID {coach.sid}: {e}')
    elif coach.service == 'telegram':
        r = send_telegram_message(coach.sid, notification_text)
    if r is True:
        return 1
    return 0


def notify_coach2(coach, **kwargs) -> int:
    if coach.service == 'facebook':
        sent = send_fb_utility_message(coach.sid, lingua=coach.lingua, **kwargs)
    elif coach.service == 'telegram':
        sent = send_telegram_message(coach.sid, **kwargs)
    else:
        logger.error(f'Unrecognized service for coach {coach.sid}: {coach.service}')
        return 0

    return int(sent)


def get_practices(team_id: str, request_start: datetime | None = None, request_end: datetime | None = None) -> list[dict] | None:
    """
    Generate a list of all practice days in the season (e.g., every Monday and Wednesday)
    if request_start and request_end dates are provided, use the intersection of season dates and date range
    """
    tz: ZoneInfo = ZoneInfo('Europe/Copenhagen')
    # Define the start and end dates for the season (e.g., from September 1 to May 31)
    practice_days: list[dict] = []
    team_info: models.Team | None = get_team_info_from_db(team_id=team_id)
    if team_info:
        team_start_date: datetime = team_info.start_date.replace(tzinfo=tz)
        team_end_date: datetime = team_info.end_date.replace(tzinfo=tz)
        start_date: datetime = team_start_date
        if request_start:
            start_date = max(team_start_date, request_start)
        end_date: datetime = team_end_date
        if request_end:
            end_date = min(team_end_date, request_end)
        cal_date: datetime = start_date
        while cal_date <= end_date:
            logger.debug(cal_date)
            event_type_l10n: str = i18n.t('app.practice').title()
            cal_weekday: int = cal_date.weekday()
            iso_week: int = cal_date.isocalendar()[1]
            if iso_week in (52, 53):
                cal_date += timedelta(days=1)
                continue

            for item in team_info.schedule:
                if item['day'] != cal_weekday:
                    continue
                weeks: str | None = item.get('weeks')  # None (every week), 'odd', or 'even'
                if weeks == 'odd' and iso_week % 2 == 0:
                    continue
                if weeks == 'even' and iso_week % 2 != 0:
                    continue

                ref: str = team_info.pairing or team_info.ref
                logger.debug(f'Adding practice for {ref} on {cal_date.strftime("%Y-%m-%d")} (weekday {cal_weekday})')
                training_times: str = item['time']
                training_times = training_times.replace('.', ':')
                times: list[str] = training_times.split('-')
                start: str = f'{cal_date.strftime("%Y-%m-%d")}T{times[0]}:00'
                end: str = f'{cal_date.strftime("%Y-%m-%d")}T{times[1]}:00'
                practice_days.append(
                    {
                        'id': f'{event_type_l10n}_{ref.replace(" ", "_")}_{cal_date.strftime("%Y%m%d")}',
                        'title': f'{event_type_l10n} {ref}',
                        'start': start,
                        'end': end,
                        'description': i18n.t('app.regular_practice_session'),
                        'allDay': False,
                    }
                )
            cal_date += timedelta(days=1)
    else:
        logger.error(f'Error fetching team information for {team_id}', 'danger')
        # TODO send telegram to ADMIN
        return None
    return practice_days


def get_events_from_file():
    trampoline_events_file = path_handler('data_path') / 'trampoline_events.json'
    events: list[dict] = []
    if (trampoline_events_file).exists():
        # if trampoline_events.json exists, then read it
        try:
            with open(trampoline_events_file, 'r', encoding='utf-8') as f:
                # f = None #inject error for testing error handling
                events = json.load(f) or []
        except json.JSONDecodeError:
            # treat empty/invalid file as no previous events
            logger.warning('Empty/invalid trampoline_events.json')
        except Exception as e:
            logger.error(f'Error reading trampoline_events.json: {e}')
            # TODO send telegram to list of admins
    return events


def get_trampoline_events(url: str = 'https://www.americakes.dk/trampoline_events.json') -> list[dict]:
    events: list[dict] = []
    try:
        response = requests.get(url=url, timeout=10)
        if response.status_code == 200:
            data = response.json()
            logger.trace(json.dumps(data, indent=2))
            if isinstance(data, list):
                events = data
            else:
                logger.error(f'Expected a list from {url}, got {type(data).__name__}')
                # TODO send to list of admins
        else:
            logger.error(f'Unexpected status {response.status_code} fetching {url}')
            # TODO send to list of admins
    except requests.exceptions.JSONDecodeError:
        logger.warning('Empty/invalid trampoline_events.json')
        # TODO send to list of admins
    except Exception as e:
        logger.error(f'Error reading JSON: {e}')
        # TODO send to list of admins
    return events


@app.route('/cal')
def calendar():
    # TODO get dept(s) from session
    type: str | None = request.args.get('type')
    teams: TeamData = []
    main_menu: str = url_for('member_menu')  # menu for members
    if type and type == 'coach':
        teams = session.get('teams', [])
        main_menu = url_for('main_menu', user=session.get('username'))  # menu for coaches
    else:
        teams = session.get('member_teams', [])
    logger.debug(f'Teams from session: {teams}')
    # team_list = ','.join([team['ref'] for team in teams])
    team_ids = ','.join([team['id'] for team in teams])
    member_id: str = session.get('member_id')
    return render_template('cal.html', member_id=member_id, lingua=get_locale(), team_list=team_ids, dept=CONVENTUS_DEPT_NAME, main_menu=main_menu)


@app.route('/api/events', methods=['GET'])
def get_events():
    request_start: datetime | None = datetime.fromisoformat(request.args.get('start')) if request.args.get('start') else None
    request_end: datetime | None = datetime.fromisoformat(request.args.get('end')) if request.args.get('end') else None
    logger.debug(f'Request start: {request.args.get("start") if request.args.get("start") else None}')
    logger.debug(f'Request end: {request.args.get("end") if request.args.get("end") else None}')
    team_list: str = request.args.get('team_list')
    logger.debug(f'Team list: {team_list}')
    # team_refs: list[str] = team_list.split(',') if team_list else []
    team_ids: list[str] = team_list.split(',') if team_list else []
    dept: str = request.args.get('dept')

    events_list: list[dict] = []
    failed_teams: list[str] = []
    for team_id in team_ids:
        practices: list[dict] | None = get_practices(team_id, request_start=request_start, request_end=request_end)

        if practices is None:
            failed_teams.append(team_id)
            continue

        for event in practices:
            events_list.append(
                {
                    'id': event.get('id'),
                    'title': event.get('title'),
                    'start': event.get('start'),  # FullCalendar maps this to the grid
                    'end': event.get('end'),
                    'description': event.get('description', ''),
                }
            )
    if failed_teams:
        if len(team_ids) == len(failed_teams):
            if len(team_ids) == 1:
                flash(i18n.t('app.cannot_fetch_team_info_your_team'), 'danger')
            else:
                flash(i18n.t('app.cannot_fetch_team_info_all_your_teams', count=len(failed_teams)), 'danger')
        else:
            flash(i18n.t('app.cannot_fetch_team_info_x_of_y_teams', count=len(failed_teams)), 'danger')
    if dept and dept == 'Trampolingymnastik':
        eid: int = 0
        for event in get_trampoline_events():
            eid += 1
            event_color = '#d20069'

            month_map = {'jan': 1, 'feb': 2, 'mar': 3, 'apr': 4, 'maj': 5, 'jun': 6, 'jul': 7, 'aug': 8, 'sep': 9, 'okt': 10, 'nov': 11, 'dec': 12}
            day: int = 0
            event_start: datetime | date | None = None
            event_end: datetime | date | None = None
            year = event.get('year')
            days = event.get('days', '')
            if not days and event.get('start') and event.get('end'):
                # 19980119T230000 (year, month, day, T, hour, minute, second)
                event_start = datetime.fromisoformat(event.get('start'))
                event_end = datetime.fromisoformat(event.get('end'))
            elif ' - ' in days:  # multiple days in format "day month - day month", e.g. 31 jan - 1 feb, split into start and end
                start, end = days.split(' - ')
                day, month_txt = start.split()
                day_end, month_txt_end = end.split()
                event_end = date(year, month_map[month_txt_end], int(day_end)) + timedelta(days=1)
            elif days and ' ' in days:  # single day in format "day month", e.g. "31 jan", split into day and month
                day, month_txt = days.split()
            else:
                logger.error(f'Unexpected value for event days: {event.get("days")}. Skipping event.')
                # TODO send notification ADMIN
                continue
            if not event_start:
                if year is None or month_txt not in month_map:
                    logger.error(f'Skipping trampoline event with unusable date: {event}')
                    continue
                event_start = date(year, month_map[month_txt], int(day))

            event_start_iso = event_start.isoformat()

            event = {
                'id': eid,
                'title': event.get('title'),
                'start': event_start_iso,  # FullCalendar maps this to the grid
                'allDay': True,
                'url': event.get('url', ''),
                'extendedProps': {
                    'place': event.get('place', ''),
                    'address': event.get('address', ''),
                    'program': event.get('program', ''),
                    'deadline': event.get('deadline', ''),
                },
                'color': event_color,
            }

            if event_end:
                event['end'] = event_end.isoformat() if event_end else None
            if 'T' in event_start_iso:
                # If the event has a time component, ensure it's treated as a timed event
                event['allDay'] = False
            logger.trace(f'Trampoline event added to list: {event}')
            events_list.append(event)
        logger.debug(f'Added {eid} trampoline events to the list for department {dept}')

    # Fetch all documents using MongoEngine ORM
    db_events: models.Events = models.Event.objects.none()  # Initialize with an empty queryset
    if team_ids or dept:
        # Fetch events based on team_ids and/or dept
        if team_ids and dept:
            db_events: models.Events = models.Event.objects(tags__in=team_ids + [dept, 'all'])
        elif team_ids:
            db_events: models.Events = models.Event.objects(tags__in=team_ids + ['all'])
        elif dept:
            db_events: models.Events = models.Event.objects(tags=[dept, 'all'])

    for event in db_events:
        events_list.append(
            {
                'id': str(event.id),
                'title': event.title,
                'start': event.start,  # FullCalendar maps this to the grid
                'description': event.description or '',
            }
        )

    return jsonify(events_list)


# =====================================================================
# FACEBOOK MESSENGER WEBHOOK ENDPOINT AND RELATED FUNCTIONS
# =====================================================================
def verify_fb_signature(raw_payload_bytes, signature_header):
    """
    Verifies that the incoming webhook payload was signed by Meta using your App Secret.
    """
    if not signature_header:
        return False

    # Strip "sha256=" from the header prefix to isolate the actual signature
    received_signature = signature_header.replace('sha256=', '')
    app_secret = os.environ.get('FB_APP_SECRET')
    if not app_secret:
        logger.error('FB_APP_SECRET not set; rejecting webhook payload')
        return False

    # Calculate the expected signature using your App Secret and raw body bytes
    expected_signature = hmac.new(key=app_secret.encode('utf-8'), msg=raw_payload_bytes, digestmod=hashlib.sha256).hexdigest()

    # Secure, timing-safe comparison
    return hmac.compare_digest(expected_signature, received_signature)


def get_fb_user_info(sid: str) -> dict | None:
    """
    Fetches user information from the Facebook Graph API.
    """
    url = f'https://graph.facebook.com/v26.0/{sid}?fields=first_name,last_name&access_token={PAGE_ACCESS_TOKEN}'
    response = requests.get(url, timeout=REQUEST_TIMEOUT)
    if response.status_code == 200:
        logger.trace(json.dumps(response.json(), indent=2))
        return response.json()
    else:
        logger.error(f'Error fetching FB user info for PSID {sid}: {response.status_code}')
        try:
            logger.debug(f'Graph API response body:\n{json.dumps(response.json(), indent=2)}')
        except ValueError:
            logger.debug(f'Graph API response body (non-JSON): {response.text}')
    return None


@app.route('/fb_webhook', methods=['GET', 'POST'])
def fb_webhook():
    logger.info('Received fb_webhook call')
    if request.method == 'GET':
        # Handle Meta's initial handshake/verification
        mode = request.args.get('hub.mode')
        token = request.args.get('hub.verify_token')
        challenge = request.args.get('hub.challenge')

        if mode == 'subscribe' and token == os.environ.get('VERIFY_TOKEN'):
            logger.info('Webhook successfully verified by Meta!')
            return challenge, 200
        return 'Verification mismatch', 403

    if request.method == 'POST':
        logger.info('Received post request from Facebook')

        # Grab raw request data for signature verification
        raw_payload = request.get_data()
        signature_header = request.headers.get('X-Hub-Signature-256')

        # Run security check
        if not verify_fb_signature(raw_payload, signature_header):
            logger.warning('Unauthorized POST request: Signature verification failed!')
            return 'Invalid signature', 403

        # Safely convert raw bytes to JSON now that it's verified
        data = request.get_json()
        logger.debug(f'Full webhook payload received:\n{json.dumps(data, indent=2)}')
        if data.get('object') == 'page':
            for entry in data.get('entry', []):
                for messaging_event in entry.get('messaging', []):
                    sid = messaging_event.get('sender', {}).get('id')
                    if sid and 'message' in messaging_event:
                        message_text = messaging_event['message'].get('text', '').strip()
                        spam_keywords = ['fund', 'grant', 'prince', 'money', 'inheritance', 'million', 'usd']
                        is_spam = any(keyword in message_text for keyword in spam_keywords)
                        if is_spam:
                            logger.info('Spam detected and silently dropped.')
                            return 'EVENT_RECEIVED', 200

                        logger.debug('Not detected as spam.')
                        messenger_success = False
                        locale = 'da'
                        if sid == '38506813588909426':
                            locale = 'en'
                        name = i18n.t('app.coach', locale=locale)
                        r = get_fb_user_info(sid)
                        if r:
                            # store code in database with sid and name, and a timestamp for expiration (e.g. 10 minutes)
                            name = r.get('first_name', '') + ' ' + r.get('last_name', '')
                            name = name.strip()
                            # locale = r.get('locale', 'da').split('-')[0] #requires pages_user_locale permissions
                        if re.match(r'^\s*link\s*Eir\s*$', message_text, re.IGNORECASE):
                            logger.debug('Message matches linking request')
                            # get info from sid using graph api and send a message back to the user
                            # generate a random 6 digit code
                            # code = ''.join(random.choices(string.ascii_uppercase + string.digits, k=6))
                            code = ''.join(secrets.choice('0123456789') for _ in range(6))
                            res: str = save_pending_link(sid, code, name, 'facebook')

                            # send response back to the user with the code
                            if res == code:
                                messenger_success = send_fb_messenger_response(
                                    sid, i18n.t('app.service_link_code', code=code, name=name, service_name='Facebook', locale=locale)
                                )
                            else:
                                # res is a string value for a localized error message
                                messenger_success = send_fb_messenger_response(sid, i18n.t(res, locale=locale))
                        elif re.match(r'^\s*(afmeldinger|signouts)\s*$', message_text, re.IGNORECASE):
                            logger.debug('Message matches update request')

                            # get signouts that match coaches teams for today
                            try:
                                content = ''
                                notifications: list[models.Notification] = get_notifications_by_sid(sid, 'facebook')
                                if not notifications:
                                    content = i18n.t('app.no_link_found', name=name, service_name='Facebook', locale=locale)
                                else:
                                    team_ids: list = notifications[0].team_ids or []
                                    if not team_ids:
                                        content = i18n.t('app.no_teams_found', name=name, service_name='Facebook', locale=locale)
                                    else:
                                        current_date = datetime.now().strftime('%Y-%m-%d')
                                        for team_id in team_ids:
                                            logger.debug(f'get_signout_list_from_db for team {team_id}')
                                            team_signouts: list[models.Signout] = get_signout_list_from_db(
                                                current_date, CONVENTUS_CLUB_ID, CONVENTUS_DEPT_ID.split('_')[-1], team_id
                                            )
                                            paired_name = get_pairing_from_team_id(team_id) or team_id
                                            if len(team_signouts) > 0:
                                                logger.debug(f'get_signout_list_from_db for team {team_id} returned {len(team_signouts)} signouts')
                                                content += f'{i18n.t("app.signout_response", team_id=paired_name, count=len(team_signouts), locale=locale)}\n'
                                                content += create_signout_details_for_coach(team_id, team_signouts)
                                            # else:
                                            #    content += f'{i18n.t("app.signout_response", team_id=paired_name, count="0")}\n'
                                        if content == '':
                                            content = i18n.t('app.no_signouts_today', locale=locale)
                            except DatabaseError as e:
                                logger.error(f'Database error occurred while fetching notifications for SID {sid}: {e}')
                                content += i18n.t('app.database_error', locale=locale)
                            except Exception as e:
                                logger.error(f'Error occurred while fetching notifications for SID {sid}: {e}')
                                content += i18n.t('app.unknown_error', locale=locale)

                            # send response back to the user with the signouts
                            messenger_success = send_fb_messenger_response(sid, content)
                        else:
                            logger.warning(f'Unrecognized message from user {sid}: {message_text}')
                        logger.info(f'FB Messenger send result: {"Success" if messenger_success else "Failed"}')  # {' checked' if checked else ''}
        return 'EVENT_RECEIVED', 200


def create_signout_details_for_coach(team_id: str, team_signouts: list[models.Signout]) -> str:
    content = ''
    csv_text = None
    if (path_handler('data_path') / f'{team_id}.html').exists():
        csv_text = (path_handler('data_path') / f'{team_id}.html').read_text()
    if not csv_text:
        logger.warning(f'Cannot read team list for team {team_id}')
        for so in team_signouts:
            logger.trace(f'{team_id} signout: {so.to_mongo().to_dict()}')
            reason_l10n = localize_reason(so.reason)
            content = f'{so.member_id}: {i18n.t("app.signed_out")} ({reason_l10n})\n'
    else:  # currently, the else will never be used because the team member download won't work from the webhook, and there is no saved
        # team member list in the data folder
        logger.trace(csv_text)
        # get team list with member_name and member_id
        team_members: list[dict] = conventus.get_members_from_csv(csv_text)  # team_members is a list of dict with "ID" and "navn" as keys
        logger.trace(f'Team members: {team_members}')
        for so in team_signouts:
            logger.trace(f'{team_id} signout: {so.to_mongo().to_dict()}')
            for tm in team_members:
                logger.debug(f'Team member info: {tm}')
                if so.member_id == tm.get('ID'):
                    # team member matched signout, add to message, then go to next signout
                    reason_l10n = localize_reason(so.reason)
                    content = f'{tm.get("Navn")}: {i18n.t("app.signed_out")} ({reason_l10n})\n'
                    break
    return content


def send_fb_messenger_response(recipient_id: str, text_content: str) -> bool:
    """
    Sends a standard text reply to a Messenger user using the Send API.
    """
    url = 'https://graph.facebook.com/v26.0/me/messages'
    params = {'access_token': PAGE_ACCESS_TOKEN}
    payload: dict = {'recipient': {'id': recipient_id}, 'messaging_type': 'RESPONSE', 'message': {'text': text_content}}

    try:
        response = requests.post(url, params=params, json=payload, timeout=REQUEST_TIMEOUT)
        response_data = response.json()

        if response.status_code == 200:
            logger.info(f'Successfully sent message to {recipient_id}')
            return True
        else:
            logger.error(f'Failed to send message: {response_data}')
            return False

    except Exception as e:
        logger.error(f'Error calling Messenger Send API: {e}')
        return False


def send_fb_event_action_notification(
    psid: str, action: str, name: str, event_type_l10n: str, team_or_event: str, date: str, comment: str = '', lingua='da', **kwargs
) -> bool:
    url = f'https://graph.facebook.com/v26.0/{os.environ.get("PAGE_ID")}/messages'
    template_name = f'event_{action}_notification'  # either signout or signup -- TODO add added, cancelled, changed
    parameters = [
        {'type': 'text', 'text': name},
        {'type': 'text', 'text': event_type_l10n},
        {'type': 'text', 'text': team_or_event},
        {'type': 'text', 'text': date},
    ]
    if comment != '':
        parameters.append({'type': 'text', 'text': comment})
    payload = {
        'recipient': {'id': psid},
        'messaging_type': 'UTILITY',  # <-- required, not RESPONSE
        'message': {
            'template': {
                'name': template_name,
                'language': {'code': lingua},
                'components': [
                    {
                        'type': 'body',
                        'parameters': parameters,
                    }
                ],
            }
        },
    }
    logger.debug(f'Sending FB event action notification with payload: {payload}')

    headers = {'Authorization': f'Bearer {PAGE_ACCESS_TOKEN}', 'Content-Type': 'application/json'}

    r = requests.post(url, json=payload, headers=headers, timeout=REQUEST_TIMEOUT)
    logger.debug(f'Status code: {r.status_code}, Text: {r.text}')
    r.raise_for_status()
    logger.info(
        f'JSON: {r.json()}'
    )  # TODO verify that there is nothing in the json that I need to look at before determining success, then change to .debug
    return True


def send_fb_member_change_notification(psid: str, changes: str, lingua='da', **kwargs) -> bool:
    url = f'https://graph.facebook.com/v26.0/{os.environ.get("PAGE_ID")}/messages'
    template_name = 'member_change_notification'
    parameters = [
        {'type': 'text', 'text': changes},
    ]
    payload = {
        'recipient': {'id': psid},
        'messaging_type': 'UTILITY',  # <-- required, not RESPONSE
        'message': {
            'template': {
                'name': template_name,
                'language': {'code': lingua},
                'components': [
                    {
                        'type': 'body',
                        'parameters': parameters,
                    }
                ],
            }
        },
    }
    logger.debug(f'Sending FB member change notification with payload: {payload}')

    headers = {'Authorization': f'Bearer {PAGE_ACCESS_TOKEN}', 'Content-Type': 'application/json'}

    r = requests.post(url, json=payload, headers=headers, timeout=REQUEST_TIMEOUT)
    logger.debug(f'Status code: {r.status_code}, Text: {r.text}')
    r.raise_for_status()
    logger.info(
        f'JSON: {r.json()}'
    )  # TODO verify that there is nothing in the json that I need to look at before determining success, then change to .debug
    return True


def send_fb_utility_message(psid: str, lingua: str, message_type: str = 'event', **kwargs) -> bool:
    dispatch = {
        'event': send_fb_event_action_notification,
        'member_changes': send_fb_member_change_notification,
    }
    fn = dispatch.get(message_type)
    if fn is None:
        logger.error(f'Error occurred while sending FB {message_type} notification: unknown message type')
        # TODO send admin notification
        return False

    try:
        send_ok: bool = fn(psid=psid, lingua=lingua, **kwargs)
    except (requests.exceptions.JSONDecodeError, requests.exceptions.HTTPError) as e:
        logger.error(f'Error occurred while sending FB {message_type} notification to PSID {psid}: {e}')
        # TODO send admin notification
        return False

    return send_ok


# =====================================================================
# TELEGRAM ENDPOINT AND RELATED FUNCTIONS
# =====================================================================
@app.route('/telegram_webhook', methods=['POST'])
def telegram_webhook():
    payload = request.get_json()
    logger.trace(f'Full webhook payload received:\n{json.dumps(payload, indent=2)}')
    if 'message' in payload and 'text' in payload['message']:
        chat_id = payload['message']['chat']['id']
        text = payload['message']['text'].strip()
        user_info = payload['message']['from']

        first_name = user_info.get('first_name', '')
        last_name = user_info.get('last_name', '')
        name = f'{first_name} {last_name}'.strip()

        try:
            # Telegram delivers deep links as "/start <parameter>"
            if text == '/start linkeir':
                # generate secure random 6-digit code
                # code = ''.join(random.choices(string.ascii_uppercase + string.digits, k=6))
                code = ''.join(secrets.choice('0123456789') for _ in range(6))

                # use language_code from user_info if available, otherwise default to 'da'
                language_code: str = user_info.get('language_code')
                logger.info(f'User language_code: {language_code}')
                if not language_code:
                    language_code = 'da'
                logger.debug(f'Using language_code: {language_code}')

                # Save `service`, `verification_code`, `chat_id`, and `expires_at` into pending document
                res: str = save_pending_link(str(chat_id), code, name, 'telegram', language_code)

                # send message with linking code back to the user via Telegram Bot API
                msg_text: str = ''
                if res == code:
                    # message the code back to the user instantly
                    msg_text = i18n.t('app.service_link_code', code=code, name=name, service_name='Telegram', locale=language_code)
                else:
                    # res is a string value for a localized error message
                    msg_text = i18n.t(res, locale=language_code)
                logger.info('Sending code to Telegram user')
                logger.debug(f'Message: {msg_text}')
                msg_text = escape_markdown_v2(msg_text)  # escape MarkdownV2
                msg_text = msg_text.replace(f'{code}', f'`{code}`')  # add bacticks to the message for tap to copy in Telegram
                logger.debug(f'Sending message to Telegram user {chat_id}: {msg_text}')
                msg_payload = {
                    'chat_id': chat_id,
                    'text': msg_text,
                    'parse_mode': 'MarkdownV2',
                    'reply_markup': {
                        'inline_keyboard': [
                            [
                                {
                                    'text': f'📋 {i18n.t("app.copy_code")}',
                                    'copy_text': {
                                        'text': code  # <--- ONLY the 6-digit string gets copied when tapped
                                    },
                                }
                            ]
                        ]
                    },
                }
                msg_url = f'https://api.telegram.org/bot{os.environ.get("EIR_TELEGRAM_TOKEN")}/sendMessage'
                headers = {'Content-Type': 'application/json'}
                tg_response = requests.post(msg_url, json=msg_payload, headers=headers, timeout=REQUEST_TIMEOUT)
                logger.info(f'Response from Telegram: {tg_response.status_code}')
                logger.debug(tg_response.json())
            else:
                logger.info(f'Ignoring message from Telegram user {chat_id}: {text}')
        except Exception as e:
            logger.error(f'Error sending message to Telegram user {chat_id}: {e}')
    return jsonify({'status': 'ok'}), 200


def send_telegram_message(chat_id: str, notification_text: str, **kwargs) -> bool:
    # anything irrelevant in the kwargs just gets ignored
    token = os.environ.get('EIR_TELEGRAM_TOKEN')
    if not token:
        logger.error('EIR_TELEGRAM_TOKEN not set')
        return False

    url = f'https://api.telegram.org/bot{token}/sendMessage'

    # Clean, basic payload—no markdown parser to trip over
    payload = {
        'chat_id': chat_id,
        'text': notification_text,
    }

    logger.debug(payload)
    try:
        response: requests.Response = requests.post(url, json=payload, timeout=REQUEST_TIMEOUT)
        logger.info(f'Response from Telegram: {response.status_code}')
        data = response.json()
        logger.debug(data)
        return data.get('ok', False)
    except ValueError:
        logger.warning(f'Non-JSON response body from Telegram: {response.text}')
    except requests.exceptions.RequestException as e:
        logger.error(f'Failed to reach Telegram: {e}')
    return False


def escape_markdown_v2(text: str) -> str:
    """Escapes all reserved characters for Telegram MarkdownV2 parsing."""
    # List of all 18 reserved characters: _ * [ ] ( ) ~ ` > # + - = | { } . !
    escape_chars = r'_*[]()~`>#+-=|{}.!'
    return re.sub(f'([{re.escape(escape_chars)}])', r'\\\1', text)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--debug', action='store_true', help='enable debug logging')
    parser.add_argument('--trace', action='store_true', help='enable trace logging')
    args = parser.parse_args()
    configure_local_logger(debug=args.debug, trace=args.trace)

    if args.debug or args.trace:
        logger.info(
            'Started flask in debug mode with debug logging enabled' if args.debug else 'Started flask in debug mode with trace logging enabled'
        )

    # start the app
    try:
        subprocess.run(['gunicorn', '--version'], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=True)
        gunicorn_args = [
            'gunicorn',
            '-w',
            '1',
            'app:app',
        ]
        os.environ['PYTHONPATH'] = 'app'
        print('--> Linux/WSL detected and Gunicorn installed: Handing execution over to Gunicorn...')
        # Use os.execvp to entirely replace the current 'python' process with a 'gunicorn' process.
        os.execvp('gunicorn', gunicorn_args)
    except (FileNotFoundError, subprocess.CalledProcessError):
        startup_msg = ''
        if os.name == 'nt':
            startup_msg = '--> Windows detected.'
        if 'Windows detected' not in startup_msg:
            startup_msg += '--> Gunicorn not found, but not running Windows. Please ensure Gunicorn is installed and in your PATH for production use.'
        startup_msg += ' Starting native Flask development server...'
        print(startup_msg)
        app.run(debug=args.debug or args.trace)
